// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRR-GO2_yt-8PY78D5hZZGP9ut884gIAM',
    appId: '1:866282442567:android:eead0194768f6af6774662',
    messagingSenderId: '866282442567',
    projectId: 'keopi-54c5c',
    storageBucket: 'keopi-54c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsezjfGvXk_8dIlIXJwnSLCVGxwj0sjPs',
    appId: '1:866282442567:ios:8cd28f604e3c2e9a774662',
    messagingSenderId: '866282442567',
    projectId: 'keopi-54c5c',
    storageBucket: 'keopi-54c5c.firebasestorage.app',
    iosBundleId: 'com.example.keopi',
  );
}
