// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNY_hm47m4UgqqsECn6trlIF5QDJYPLng',
    appId: '1:898932544803:web:81c50241c29213c37d6896',
    messagingSenderId: '898932544803',
    projectId: 'keopiv2',
    authDomain: 'keopiv2.firebaseapp.com',
    storageBucket: 'keopiv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwjEgryVTuXpTZNYdjPsg7LywD9B3YbA',
    appId: '1:898932544803:android:96c2cea9fb15e18d7d6896',
    messagingSenderId: '898932544803',
    projectId: 'keopiv2',
    storageBucket: 'keopiv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1HGPL0pemQiUcTBoWn8KL7DYtnqXmas',
    appId: '1:898932544803:ios:baddf1bc0b9df5447d6896',
    messagingSenderId: '898932544803',
    projectId: 'keopiv2',
    storageBucket: 'keopiv2.firebasestorage.app',
    iosBundleId: 'com.keopi.keopi',
  );
}
